/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package LibraryManagement;

/**
 *
 * @author saign
 */
public class adminpage extends javax.swing.JFrame {

    /**
     * Creates new form adminpage
     */
    public adminpage() {
        super("ADMIN LOGIN");
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">                          
    private void initComponents() {

        jMenu1 = new javax.swing.JMenu();
        jMenu6 = new javax.swing.JMenu();
        jMenuItem3 = new javax.swing.JMenuItem();
        jPanel1 = new javax.swing.JPanel();
        jMenuBar1 = new javax.swing.JMenuBar();
        New = new javax.swing.JMenu();
        addstudent = new javax.swing.JMenuItem();
        addbook = new javax.swing.JMenuItem();
        view = new javax.swing.JMenu();
        viewstudent = new javax.swing.JMenuItem();
        viewbook = new javax.swing.JMenuItem();
        jMenuItem1 = new javax.swing.JMenuItem();
        remove = new javax.swing.JMenu();
        remstudent = new javax.swing.JMenuItem();
        rembook = new javax.swing.JMenuItem();
        logout = new javax.swing.JMenu();

        jMenu1.setText("jMenu1");

        jMenu6.setText("jMenu6");

        jMenuItem3.setText("jMenuItem3");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );

        New.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED, java.awt.Color.gray, java.awt.Color.lightGray, null, java.awt.Color.darkGray));
        New.setText("New");
        New.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        New.setIconTextGap(10);
        New.setMargin(new java.awt.Insets(8, 8, 3, 8));
        New.setMaximumSize(new java.awt.Dimension(50, 32767));
        New.addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseDragged(java.awt.event.MouseEvent evt) {
                NewMouseDragged(evt);
            }
        });
        New.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                NewMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                NewMouseEntered(evt);
            }
        });

        addstudent.setText("Add Student");
        addstudent.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                addstudentActionPerformed(evt);
            }
        });
        New.add(addstudent);

        addbook.setText("Add Book");
        addbook.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                addbookActionPerformed(evt);
            }
        });
        New.add(addbook);

        jMenuBar1.add(New);

        view.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED, java.awt.Color.lightGray, java.awt.Color.lightGray, java.awt.Color.black, java.awt.Color.gray));
        view.setText("view");
        view.setMargin(new java.awt.Insets(3, 116, 3, 116));
        view.setMaximumSize(new java.awt.Dimension(50, 32767));

        viewstudent.setText("Students");
        viewstudent.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                viewstudentActionPerformed(evt);
            }
        });
        view.add(viewstudent);

        viewbook.setText("books");
        viewbook.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                viewbookActionPerformed(evt);
            }
        });
        view.add(viewbook);

        jMenuItem1.setText("books Issued");
        jMenuItem1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem1ActionPerformed(evt);
            }
        });
        view.add(jMenuItem1);

        jMenuBar1.add(view);

        remove.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED, java.awt.Color.gray, java.awt.Color.lightGray, java.awt.Color.black, java.awt.Color.darkGray));
        remove.setText("Remove");
        remove.setMargin(new java.awt.Insets(3, 16, 6, 16));
        remove.setMaximumSize(new java.awt.Dimension(70, 32767));

        remstudent.setText("Student");
        remstudent.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                remstudentActionPerformed(evt);
            }
        });
        remove.add(remstudent);

        rembook.setText("Book");
        rembook.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rembookActionPerformed(evt);
            }
        });
        remove.add(rembook);

        jMenuBar1.add(remove);

        logout.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED, java.awt.Color.lightGray, java.awt.Color.black, java.awt.Color.darkGray, java.awt.Color.gray));
        logout.setText("Log out");
        logout.setMaximumSize(new java.awt.Dimension(70, 32767));
        logout.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                logoutMouseClicked(evt);
            }
        });
        jMenuBar1.add(logout);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 400, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 279, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>                        

    private void addbookActionPerformed(java.awt.event.ActionEvent evt) {                                        
        // TODO add your handling code here:
        new addbook().setVisible(true);
    }                                       

    private void NewMouseEntered(java.awt.event.MouseEvent evt) {                                 
        // TODO add your handling code here:
    }                                

    private void addstudentActionPerformed(java.awt.event.ActionEvent evt) {                                           
        // TODO add your handling code here:
        new addstudent().setVisible(true);
    }                                          

    private void viewstudentActionPerformed(java.awt.event.ActionEvent evt) {                                            
        // TODO add your handling code here:
        new viewStudent().setVisible(true);
    }                                           

    private void remstudentActionPerformed(java.awt.event.ActionEvent evt) {                                           
        // TODO add your handling code here:
        new remst().setVisible(true);
    }                                          

    private void NewMouseDragged(java.awt.event.MouseEvent evt) {                                 
        // TODO add your handling code here:
        
    }                                

    private void NewMouseClicked(java.awt.event.MouseEvent evt) {                                 
        // TODO add your handling code here:
    }                                

    private void viewbookActionPerformed(java.awt.event.ActionEvent evt) {                                         
        // TODO add your handling code here:
        new viewbook().setVisible(true);
    }                                        

    private void logoutMouseClicked(java.awt.event.MouseEvent evt) {                                    
        // TODO add your handling code here:
        this.setVisible(false);
    }                                   

    private void jMenuItem1ActionPerformed(java.awt.event.ActionEvent evt) {                                           
        // TODO add your handling code here:
        new issuedbook().setVisible(true);
    }                                          

    private void rembookActionPerformed(java.awt.event.ActionEvent evt) {                                        
        // TODO add your handling code here:
        new rembook().setVisible(true);
    }                                       

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(adminpage.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(adminpage.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(adminpage.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(adminpage.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new adminpage().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify                     
    private javax.swing.JMenu New;
    private javax.swing.JMenuItem addbook;
    private javax.swing.JMenuItem addstudent;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenu jMenu6;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JMenuItem jMenuItem1;
    private javax.swing.JMenuItem jMenuItem3;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JMenu logout;
    private javax.swing.JMenuItem rembook;
    private javax.swing.JMenu remove;
    private javax.swing.JMenuItem remstudent;
    private javax.swing.JMenu view;
    private javax.swing.JMenuItem viewbook;
    private javax.swing.JMenuItem viewstudent;
    // End of variables declaration                   
}
