/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package LibraryManagement;
import java.sql.*;
//import java.util.*;
import javax.swing.JOptionPane;
/**
 *
 * @author saign
 */
public class borrowBook extends javax.swing.JFrame {
    static String sid;
    /**
     * Creates new form borrowBook
     */
    public borrowBook() {
        super("Borrow Book");
        initComponents();
    }
    public void getid(String s){
    sid=s;
    //return s;
}

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">                          
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        bookid = new javax.swing.JTextField();
        jButton3 = new javax.swing.JButton();
        bn = new javax.swing.JTextField();
        si = new javax.swing.JTextField();
        sn = new javax.swing.JTextField();
        q = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel1.setText("BORROW BOOK");
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(109, 22, -1, -1));

        jLabel2.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel2.setText("BOOK ID");
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(14, 53, -1, -1));

        jLabel3.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel3.setText("BOOK NAME");
        getContentPane().add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(14, 120, -1, -1));

        jLabel4.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel4.setText("STUDENT ID");
        getContentPane().add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(14, 154, 89, -1));

        jLabel5.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel5.setText("STUDENT NAME");
        getContentPane().add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(14, 188, -1, -1));

        jLabel6.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel6.setText("QUANTITY");
        getContentPane().add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(14, 222, -1, -1));

        jButton1.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jButton1.setText("CONFIRM");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 256, -1, -1));

        jButton2.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jButton2.setText("CANCEL");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton2, new org.netbeans.lib.awtextra.AbsoluteConstraints(215, 256, -1, -1));
        getContentPane().add(bookid, new org.netbeans.lib.awtextra.AbsoluteConstraints(189, 53, 213, -1));

        jButton3.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jButton3.setText("ENTER");
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton3, new org.netbeans.lib.awtextra.AbsoluteConstraints(189, 87, -1, -1));
        getContentPane().add(bn, new org.netbeans.lib.awtextra.AbsoluteConstraints(189, 120, 213, -1));
        getContentPane().add(si, new org.netbeans.lib.awtextra.AbsoluteConstraints(189, 154, 213, -1));
        getContentPane().add(sn, new org.netbeans.lib.awtextra.AbsoluteConstraints(189, 188, 213, -1));
        getContentPane().add(q, new org.netbeans.lib.awtextra.AbsoluteConstraints(189, 222, 213, -1));

        pack();
    }// </editor-fold>                        

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {                                         
        // TODO add your handling code here:
        int bkid=Integer.parseInt(bookid.getText());
        try{
            ConnectionClass connect=new ConnectionClass();
            String s="select * from books where bookId='"+bkid+"'";
            ResultSet rs=connect.st.executeQuery(s);
            while(rs.next()){
                bn.setText(rs.getString("bookName"));
                bn.setEditable(false);
                q.setText(rs.getString("quantity"));
                q.setEditable(false);
            }
            s="select * from student where StudentId='"+sid+"'";
            rs=connect.st.executeQuery(s);
            while(rs.next()){
                si.setText(rs.getString("StudentId"));
                si.setEditable(false);
                sn.setText(rs.getString("StudentName"));
                sn.setEditable(false);
            }
        }
        catch(Exception e){
            e.printStackTrace();
        }
        
    }                                        

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {                                         
        // TODO add your handling code here:
        int bid=Integer.parseInt(bookid.getText());
        String bon=bn.getText();
        String sti=si.getText();
        String stn=sn.getText();
        int qu=Integer.parseInt(q.getText());
        String date=new java.util.Date().toString();
        try{
            if(qu<=0){
                JOptionPane.showMessageDialog(null,"THERE ARE NO BOOKS AVAILABLE");
            }  
            else{
            ConnectionClass connect=new ConnectionClass();
            String s1="insert into issuedbook(bookId,bookName,studentId,studentName,date) values('"+bid+"','"+bon+"','"+sti+"','"+stn+"','"+date+"')";
            String s2="update books set Issued=Issued+1 where bookId='"+bid+"'";
            String s3="update books set quantity=quantity-1 where bookId='"+bid+"'";
            int a1=connect.st.executeUpdate(s1);
            int a2=connect.st.executeUpdate(s2);
            int a3=connect.st.executeUpdate(s3);
            if(a1==1||a2==1||a3==1){
                JOptionPane.showMessageDialog(null,"YOUR BOOK IS ISSUED");
                this.setVisible(false);
            }
            else{
                JOptionPane.showMessageDialog(null,"THERE IS AN ERROR PLEASE CHECK AGAIN");
            }
            }
        }
        catch(Exception e){
            e.printStackTrace();
        }
    }                                        

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {                                         
        // TODO add your handling code here:
        this.setVisible(false);
    }                                        

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(borrowBook.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(borrowBook.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(borrowBook.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(borrowBook.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new borrowBook().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify                     
    private javax.swing.JTextField bn;
    private javax.swing.JTextField bookid;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JTextField q;
    private javax.swing.JTextField si;
    private javax.swing.JTextField sn;
    // End of variables declaration                   
}
